# Header
menu:
  首页: /#blog

# Site favicon
favicon: images/favicon.ico

# Site logo
# logo: /avatar.png

# Enable Mathjax
# mathjax: false

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false